"""create applications table

Revision ID: 161abf04fca0
Revises: af1a656c8c80
Create Date: 2026-03-21 02:34:37.702835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161abf04fca0'
down_revision: Union[str, Sequence[str], None] = 'af1a656c8c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index('ix_applications_user_source', 'applications', ['user_id', 'source'], unique=False)
    op.create_index('ix_applications_user_stage', 'applications', ['user_id', 'stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_user_stage', table_name='applications')
    op.drop_index('ix_applications_user_source', table_name='applications')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
