"""index reminder_date for scheduler performance

Revision ID: 79b668d4d64e
Revises: 9c24ec66da99
Create Date: 2026-05-14 00:53:53.157228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b668d4d64e'
down_revision: Union[str, Sequence[str], None] = '9c24ec66da99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_reminder_date'), 'applications', ['reminder_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_reminder_date'), table_name='applications')
    # ### end Alembic commands ###
