"""add reminder_date to applications

Revision ID: 9c24ec66da99
Revises: 865b2fb4cb7e
Create Date: 2026-05-05 20:45:38.046444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c24ec66da99'
down_revision: Union[str, Sequence[str], None] = '865b2fb4cb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('reminder_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'reminder_date')
    # ### end Alembic commands ###
