"""composite index on user_id,
  applied_date for velocity query

Revision ID: ca77571797a9
Revises: 79b668d4d64e
Create Date: 2026-05-19 21:46:36.663620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca77571797a9'
down_revision: Union[str, Sequence[str], None] = '79b668d4d64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_applications_user_applied_date', 'applications', ['user_id', 'applied_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_user_applied_date', table_name='applications')
    # ### end Alembic commands ###
